kind: Pod
apiVersion: v1
metadata:
   name: dnsupdater-pod
   labels:
     name: dnsupdater
spec:
  volumes:
  - name: keys
    secret:
      secretName: dnsupdater-keys
      defaultMode: 256
  containers:
  - name: dnsupdater
    image: quay.io/xens/dnsupdater
    env:
    - name: A_RECORD
      value: "test.example.com"
    - name: AUTHORITATIVE
      value: "example.com"
    - name: REMOTE_COMMAND
      value: "updatedns.sh"
    - name: REMOTE_IP
      value: "example.com"
    - name: REMOTE_USER
      value: "dns"
    volumeMounts:
    - name: keys
      readOnly: true
      mountPath: /keys
