apiVersion: v1
kind: ReplicationController
metadata:
  name: dnsupdater
spec:
  replicas: 3
  selector:
    name: dnsupdater
  template:
    metadata:
      name: dnsupdater
      labels:
        name: dnsupdater
    spec:
      containers:
      - name: dnsupdater
        image: quay.io/xens/dnsupdater

