apiVersion: v1
kind: ReplicationController
metadata:
  name: dnsupdater
spec:
  replicas: 3
  selector:
    name: dnsupdater
  template:
    metadata:
      name: dnsupdater
      labels:
        name: dnsupdater
    spec:
      volumes:
      - name: keys
        secret:
          secretName: dnsupdater-keys
          defaultMode: 256
      containers:
      - name: dnsupdater
        image: quay.io/xens/dnsupdater
        env:
        - name: A_RECORD
          value: "test.example.com"
        - name: AUTHORITATIVE
          value: "example.com"
        - name: REMOTE_COMMAND
          value: "updatedns.sh"
        - name: REMOTE_IP
          value: "example.com"
        - name: REMOTE_USER
          value: "dns"
        volumeMounts:
        - name: keys
          readOnly: true
          mountPath: /keys
